# Generated by Django 2.0.9 on 2018-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_auto_20181207_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='qb_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id from QuickBooks'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='qb_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id from QuickBooks'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Tracking number'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='qb_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id from QuickBooks'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='qb_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id from QuickBooks'),
        ),
    ]
