# Generated by Django 2.0.9 on 2018-12-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_auto_20181218_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='qb_id',
        ),
    ]
