# Generated by Django 2.0.9 on 2018-12-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0004_remove_purchaseorderitem_qb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.UserCompany', verbose_name='Company'),
        ),
    ]
