export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const TOKEN_VALID = 'TOKEN_VALID';
export const TOKEN_INVALID = 'TOKEN_INVALID';
export const INITIAL_VALIDATION_DONE = 'INITIAL_VALIDATION_DONE';

export const AUTHENTICATE_CUSTOMER = 'AUTHENTICATE_CUSTOMER';
export const AUTHENTICATION_SUCCEED = 'AUTHENTICATION_SUCCEED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATING_SUCCEED = 'CREATING_SUCCEED';
export const CREATING_FAILED = 'CREATING_FAILED';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESHING_SUCCEED = 'REFRESHING_SUCCEED';
export const REFRESHING_FAILED = 'REFRESHING_FAILED';
