# Generated by Django 2.0.9 on 2018-12-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
        ('users', '0002_auto_20181205_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='UserCompany',
        ),
    ]
