# Generated by Django 2.0.9 on 2018-12-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181207_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisteredTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserCompany')),
            ],
        ),
        migrations.AddField(
            model_name='extenduser',
            name='isManager',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='tier',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
